stages:
  - module-pipelines

helm-deploy:
  stage: module-pipelines
  trigger:
    include:
      - "/kubernetes/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - kubernetes/momo-store/**/*
