---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret-helm
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "momo-store.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson }}
type: kubernetes.io/dockerconfigjson
