apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Chart.Name }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gorlym2699@yandex.ru
    privateKeySecretRef:
      name: letsencrypt-{{ .Chart.Name }}
    solvers:
    - http01:
        ingress:
          class: nginx
