apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Chart.Name }}-{{ .Values.global.environment }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencryptEmail }}
    privateKeySecretRef:
      name: letsencrypt-{{ .Chart.Name }}-{{ .Values.global.environment }}
    solvers:
    - http01:
        ingress:
          class: nginx
