---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "momo-store.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {

      listen  {{ .Values.port | int }};

      root  /usr/share/nginx/html;
      include /etc/nginx/mime.types;

      location / {
          try_files $uri $uri/ /index.html;
      }

      location /rest/ {
        proxy_pass  http://momo-backend:{{ .Values.global.backendPort | int }}/;
      }

      location /check {
        root   /usr/share/nginx/html;
        index  check.html;
        try_files $uri $uri/ /check.html;
      }

    }
