---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-{{ .Chart.Name }}-{{ .Values.global.environment }}"
  labels:
    {{- include "momo-store.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ .Values.fqdn }}
      secretName: letsencrypt
  rules:
  - host: {{ .Values.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.port }}
