secrets:
  dockerConfigJson: "ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9"

global:
  backendPort: 8080
  appName: momo-store
  environment: staging
  imageRegistry: gitlab.praktikum-services.ru:5050/anton-alekseyev/momo-store

backend:
  name: momo-backend
  revisionHistoryLimit: 15
  replicas: 3
  monitor:
    port: 8080
    scrape: true
    endpoint: /metrics
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 20%
  image:
    name: "momo-backend"
    tag: "1.0.237235"
  hpa:
    resources:
      minReplicas: 1
      maxReplicas: 5
      averageUtilization: 75

frontend:
  name: momo-frontend
  fqdn: "momo-store-test.virtulab-services.ml"
  letsencryptEmail: "gorlym2699@gmail.com"
  port: 80
  replicas: 1
  monitor:
    port: 80
    scrape: true
    endpoint: /metrics
  image:
    name: "momo-frontend"
    tag: "1.0.237234"
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
